version: 2.1

executors:
  arm64-rust:
    docker:
      - image: arm64v8/ubuntu:22.04
    working_directory: ~/repo

jobs:
  build-arm64:
    executor: arm64-rust
    steps:
      - checkout

      - run:
          name: Temel paketleri güncelle ve kur
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              curl build-essential pkg-config libssl-dev git ca-certificates

      - run:
          name: Rust kurulumu (rustup)
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            rustup default stable
            rustup target add aarch64-unknown-linux-gnu

      - run:
          name: Çevresel değişkenleri ayarla
          command: |
            echo 'export OPENSSL_DIR=/usr/lib/aarch64-linux-gnu' >> $BASH_ENV
            echo 'export OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu' >> $BASH_ENV
            echo 'export OPENSSL_INCLUDE_DIR=/usr/include/openssl' >> $BASH_ENV
            echo 'export PKG_CONFIG_ALLOW_CROSS=1' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Debug derlemesi
          command: |
            source $HOME/.cargo/env
            cargo build --target aarch64-unknown-linux-gnu

      - run:
          name: Release derlemesi
          command: |
            source $HOME/.cargo/env
            cargo build --release --target aarch64-unknown-linux-gnu

      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/aarch64-unknown-linux-gnu/debug/
            - target/aarch64-unknown-linux-gnu/release/

workflows:
  build:
    jobs:
      - build-arm64
