version: 2.1

jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Build for aarch64 target
          command: |
            rustup target add aarch64-unknown-linux-gnu
            cargo build --target aarch64-unknown-linux-gnu --release

workflows:
  build_and_test:
    jobs:
      - build
