version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/base:2023.06
    working_directory: ~/project

jobs:
  build-aarch64:
    executor: ubuntu-executor
    steps:
      - checkout

      - run:
          name: Install cross-compilation dependencies
          command: |
            sudo dpkg --add-architecture arm64
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu

      - run:
          name: Install Rust target
          command: rustup target add aarch64-unknown-linux-gnu

      - run:
          name: Create .cargo/config.toml for cross linker
          command: |
            mkdir -p ~/.cargo
            echo '[target.aarch64-unknown-linux-gnu]' > ~/.cargo/config.toml
            echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml
            echo 'rustflags = ["-L", "/usr/lib/aarch64-linux-gnu"]' >> ~/.cargo/config.toml

      - run:
          name: Build Debug
          command: cargo build --target aarch64-unknown-linux-gnu

      - run:
          name: Build Release
          command: cargo build --target aarch64-unknown-linux-gnu --release

      - persist_to_workspace:
          root: ~/project
          paths:
            - target/aarch64-unknown-linux-gnu/debug/
            - target/aarch64-unknown-linux-gnu/release/

workflows:
  build:
    jobs:
      - build-aarch64
