version: 2.1

executors:
  arm64-executor:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium

jobs:
  build:
    executor: arm64-executor
    steps:
      - checkout
      - run:
          name: OpenSSL ve Rust yükle
          command: |
            sudo DEBIAN_FRONTEND=noninteractive apt-get update
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
              build-essential \
              libssl-dev \
              curl
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
      - run:
          name: Rust projesini debug modunda derle
          command: |
            source $HOME/.cargo/env
            cargo build
            cp target/debug/ktp target/debug/ktp-0.1.0-debug-arm64
      - store_artifacts:
          path: target/debug/ktp-0.1.0-debug-arm64
          destination: ktp-debug
      - run:
          name: Rust projesini release modunda derle
          command: |
            source $HOME/.cargo/env
            cargo build --release
            cp target/release/ktp target/release/ktp-0.1.0-arm64
      - store_artifacts:
          path: target/release/ktp-0.1.0-arm64
          destination: ktp-release

workflows:
  version: 2
  build:
    jobs:
      - build
