name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rosetta and tools
        run: |
          softwareupdate --install-rosetta --agree-to-license
          brew install openssl rust git gh

      - name: Authenticate gh CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Build Rust debug
        run: |
          cargo build
          cp target/debug/ktp target/debug/ktp-0.1.0-debug-macos-arm

      - name: Build Rust release
        run: |
          cargo build --release
          cp target/release/ktp target/release/ktp-0.1.0-macos-arm

      - name: Create or update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.1.0
          artifacts: |
            target/debug/ktp-0.1.0-debug-macos-arm
            target/release/ktp-0.1.0-macos-arm
          token: ${{ secrets.GH_TOKEN }}
          allowUpdates: true
          makeLatest: true
