name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rosetta and tools
        run: |
          softwareupdate --install-rosetta --agree-to-license
          brew install openssl rust git gh

      - name: Build Rust debug
        run: |
          cargo build
          cp target/debug/ktp target/debug/ktp-0.1.0-debug-macos-arm

      - name: Build Rust release
        run: |
          cargo build --release
          cp target/release/ktp target/release/ktp-0.1.0-macos-arm

      - name: Create or update GitHub Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: v0.1.0
          release_name: "v0.1.0 macOS ARM"
          body: |
            ### Yeni Özellikler
            - ARM (M1/M2) için derleme desteği eklendi.
            - Debug ve Release modları için ayrı ikili dosyalar sunuluyor.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        if: ${{ steps.release.outputs.upload_url }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/debug/ktp-0.1.0-debug-macos-arm
            target/release/ktp-0.1.0-macos-arm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
