name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rosetta and tools
        run: |
          softwareupdate --install-rosetta --agree-to-license
          brew install openssl rust git gh

      - name: Build Rust debug
        run: |
          cargo build
          cp target/debug/ktp target/debug/ktp-0.1.0-debug-macos-arm

      - name: Build Rust release
        run: |
          cargo build --release
          cp target/release/ktp target/release/ktp-0.1.0-macos-arm

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GH_TOKEN}"

      - name: Create or update GitHub Release
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh release view v0.1.0 || gh release create v0.1.0 \
            target/debug/ktp-0.1.0-debug-macos-arm \
            target/release/ktp-0.1.0-macos-arm \
            --title "v0.1.0 macOS ARM" \
            --notes "ARM (M1/M2) build"
