name: KTP Rust AARCH64 Build (Debug & Release)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies (GPG, Rust, GCC AARCH64)
        run: |
          apt-get update && apt-get install -y \
            curl build-essential gcc-aarch64-linux-gnu \
            gnupg2 ca-certificates pkg-config

          # Rust kurulumu
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup target add aarch64-unknown-linux-gnu

      - name: Build (Debug)
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo build --target aarch64-unknown-linux-gnu

      - name: Build (Release)
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo build --target aarch64-unknown-linux-gnu --release

      - name: Upload Artifacts (Debug + Release)
        uses: actions/upload-artifact@v3
        with:
          name: KTP-aarch64
          path: |
            target/aarch64-unknown-linux-gnu/debug/ktp
            target/aarch64-unknown-linux-gnu/release/ktp
