name: Build for aarch64 (Debug & Release)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/upload-artifact@v4


    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Add aarch64 target
      run: rustup target add aarch64-unknown-linux-gnu

    - name: Build Debug
      run: cargo build --target aarch64-unknown-linux-gnu

    - name: Build Release
      run: cargo build --target aarch64-unknown-linux-gnu --release

    - name: Upload Debug artifact
      uses: actions/upload-artifact@v3
      with:
        name: aarch64-debug
        path: target/aarch64-unknown-linux-gnu/debug/

    - name: Upload Release artifact
      uses: actions/upload-artifact@v3
      with:
        name: aarch64-release
        path: target/aarch64-unknown-linux-gnu/release/
