name: Build for aarch64 (Debug & Release)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Rust target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install cross-compilation dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            libc6-dev:arm64 \
            libssl-dev:arm64 \
            libssh2-1-dev:arm64 \
            libgit2-dev:arm64

      - name: Create .cargo/config.toml for cross linker
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' > .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml
          echo 'rustflags = ["-L", "/usr/lib/aarch64-linux-gnu"]' >> .cargo/config.toml

      - name: Build Debug
        run: cargo build --target aarch64-unknown-linux-gnu

      - name: Build Release
        run: cargo build --target aarch64-unknown-linux-gnu --release

      - name: Upload Debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-debug
          path: target/aarch64-unknown-linux-gnu/debug/

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-release
          path: target/aarch64-unknown-linux-gnu/release/
