name: Build for aarch64 (Debug & Release)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [debug, release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install cross-compilation dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev:arm64

      - name: Build ${{ matrix.build-type }}
        run: cargo build --target aarch64-unknown-linux-gnu --${{ matrix.build-type }}

      - name: Upload ${{ matrix.build-type }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-${{ matrix.build-type }}
          path: target/aarch64-unknown-linux-gnu/${{ matrix.build-type }}/
