name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rosetta and dependencies
        run: |
          softwareupdate --install-rosetta --agree-to-license
          brew install openssl rust git gh

      - name: Build Rust debug
        run: |
          cargo build
          cp target/debug/ktp target/debug/ktp-0.1.0-debug-macos-arm

      - name: Build Rust release
        run: |
          cargo build --release
          cp target/release/ktp target/release/ktp-0.1.0-macos-arm

      - name: Create or update GitHub Release
        run: |
          if ! gh release view $GITHUB_REF_NAME >/dev/null 2>&1; then
            gh release create $GITHUB_REF_NAME \
              target/debug/ktp-0.1.0-debug-macos-arm \
              target/release/ktp-0.1.0-macos-arm \
              --title "$GITHUB_REF_NAME macOS ARM" \
              --notes "ARM (M1/M2) build"
          else
            gh release upload $GITHUB_REF_NAME \
              target/debug/ktp-0.1.0-debug-macos-arm \
              target/release/ktp-0.1.0-macos-arm --clobber
          fi
